-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."FactSale"
(
    rowid integer NOT NULL,
    bookID INTEGER, 
    locationID INTEGER, 
    dateID INTEGER, 
    sale INTEGER,
    PRIMARY KEY (rowid)
);

CREATE TABLE public."DimDate"
(
    dateID integer NOT NULL,
    yearID integer ,
    monthID integer ,
    dayID integer ,
    PRIMARY KEY (dateID)
);

CREATE TABLE public."DimLocation"
(
    locationID integer NOT NULL,
    city CHAR,
    region CHAR ,
    PRIMARY KEY (locationID)
);

CREATE TABLE public."DimBook"
(
    bookID integer NOT NULL,
    book CHAR,
    genre CHAR ,
    PRIMARY KEY (bookID)
);

ALTER TABLE public."FactSale"
    ADD FOREIGN KEY (bookID)
    REFERENCES public."DimBook" (bookID)
    NOT VALID;


ALTER TABLE public."FactSale"
    ADD FOREIGN KEY (locationID)
    REFERENCES public."DimLocation" (locationID)
    NOT VALID;
    
ALTER TABLE public."FactSale"
    ADD FOREIGN KEY (dateID)
    REFERENCES public."DimDate" (dateID)
    NOT VALID;
END;